server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui.html
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: pw
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true